### ISSUE TITLE
font definitions in theme.css conflict with author definitions

### ISSUE THREAD

**Issue by myakura** [pxgrid/aigis#114]
Hi.
I just found that [theme.css defines `font-family` and `font-size` in `body`](https://github.com/pxgrid/aigis/blob/17c808ace4847e016e31343c87c43792fd87de1d/examples/aigis_assets/css/theme.css#L427-L428). 

```css
body {
  margin: 0;
  padding: 0;
  font-family: "Helvetica Neue",Helvetica,arial,nimbussansl,liberationsans,freesans,clean,sans-serif,"Segoe UI Emoji","Segoe UI Symbol";
  font-size: 1rem; }
```

I find this problematic; the stylesheets on which I'm currently working specify font styles in `html` but not in`body` so those font styles overrides mine.

I know this theme.css is kinda "as a bonus" thing; yeah we can define our own styles. But I still feel those `font-family` and `font-size` in `body` a bit opinionated.
If you want to specify font styles for the template, you might wanna do on `.aigis-**` instead of `body`.

```css
[class^="aigis-"] {
  font-family: "Helvetica Neue",Helvetica,arial,nimbussansl,liberationsans,freesans,clean,sans-serif,"Segoe UI Emoji","Segoe UI Symbol";
  font-size: 1rem; 
}
/* we may use `[class|=aigis]` but I feel it's too smart */
```

wdyt?
