### ISSUE TITLE
scssで@importを使うとエラー

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#12]
config.yaml

```yaml
name: test_project
source: ./static/css/sass.scss
format: yaml
dest: ./docs
dependencies:
  - ./static
  - ./doc_assets
template: ./custom_template
timestamp_format: YYYY/MM/DD/ HH:mm
highlight_theme: dracula
md_class:
  heading:
    - hoge
  listitem:
    - hogehoge
inject:
  - html
  - jade
  - js
  - coffee
highlight: true
index: ./styleguide.md
```

sass.scssの中身
`sass.scss`と同じ階層にmoduleディレクトリを設置して、`_mod.scss`を追加

```
@import 'module/mod';
```

実行時のエラー

```zsh
[geckotang]$ node index.js

-------- target file --------

Error: file to import not found or unreadable: module/mod
Current dir:
  at Object.module.exports.renderSync (/Users/geckotang/Desktop/Aigis/node_modules/node-sass/lib/index.js:409:22)
  at sass (/Users/geckotang/Desktop/Aigis/lib/parser/sass.js:5:18)
  at /Users/geckotang/Desktop/Aigis/lib/parser/css.js:22:40
  at LazyWrapper.lazyValue [as value] (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:1147:28)
  at baseWrapperValue (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:2750:25)
  at LodashWrapper.wrapperValue (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:5730:14)
  at LazyWrapper.lazyValue [as value] (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:1105:36)
  at baseWrapperValue (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:2750:25)
  at LodashWrapper.wrapperValue (/Users/geckotang/Desktop/Aigis/node_modules/lodash/index.js:5730:14)
  at Aigis.parseCSS (/Users/geckotang/Desktop/Aigis/lib/parser/css.js:88:6)
  at Aigis.setup (/Users/geckotang/Desktop/Aigis/lib/Aigis.js:45:27)
  at Aigis._onEndLoadCSSFiles (/Users/geckotang/Desktop/Aigis/lib/Aigis.js:34:12)
  at EventEmitter.listener (/Users/geckotang/Desktop/Aigis/node_modules/eventemitter2/lib/eventemitter2.js:251:10)
  at EventEmitter.emit (/Users/geckotang/Desktop/Aigis/node_modules/eventemitter2/lib/eventemitter2.js:317:21)
  at endLoadFiles (/Users/geckotang/Desktop/Aigis/lib/reader/css.js:47:14)
  at DestroyableTransform.<anonymous> (/Users/geckotang/Desktop/Aigis/lib/reader/css.js:34:7)
  at DestroyableTransform.EventEmitter.emit (events.js:117:20)
  at /Users/geckotang/Desktop/Aigis/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:415:13)
```
