### ISSUE TITLE
コンパイル時にaigis-marked内部でエラー 

### ISSUE THREAD

**Issue by goodtea0223** [pxgrid/aigis#120]
aigisバージョン：1.3.0
 #nodeバージョン：6.9.2
npmバージョン：3.10.9

実行した際に `aigis-marked` モジュール内の `prismjs` でエラーが出てしまいコンパイルできません。
`TypeError: Cannot read property 'inside' of undefined`

以前までは問題なく実行できていたため、依存モジュールのアップデートでエラーが出るようになったと思われます。

エラーと設定の詳細は以下になります。
現状コードの `throw new Error(e);` だとエラーの詳細まで出ないのでご注意ください。
https://github.com/pxgrid/aigis/blob/master/lib/Aigis.js#L103

error
```
TypeError: Cannot read property 'inside' of undefined
    at Object.<anonymous> (node_modules/prismjs/components/prism-django.js:32:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at node_modules/aigis-marked/lib/highlight.js:20:3
    at arrayEach (node_modules/aigis-marked/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (node_modules/aigis-marked/node_modules/lodash/lodash.js:9359:14)
    at Object.<anonymous> (node_modules/aigis-marked/lib/highlight.js:19:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
From previous event:
    at Aigis.run (node_modules/node-aigis/lib/Aigis.js:98:10)
```

aigis_config.yml
```yml
name: styleguide

# The directory containing the source files to parse recursively
source: ../scss
source_type: .scss

# The directory that aigis will build to
dest: ../../public/styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_jade
template_engine: jade
```
