### ISSUE TITLE
sourceに単一ファイルを指定するとエラー

### ISSUE THREAD

**Issue by nakajmg** [pxgrid/aigis#69]
```yaml
source: ./style.css
dest: ./styleguide
dependencies:
  - ./style.css
  - ../highlight.css
  - ../theme.css
```

```
[Info] Config File: /demo/demo1.yml
[Info] Start: Generate Styleguide
Unhandled rejection Error
    at /demo/node_modules/node-aigis/lib/Aigis.js:85:17
    at tryCatcher (/demo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/demo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/demo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/demo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/demo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/demo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/demo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
