### ISSUE TITLE
Want to import README.md

### ISSUE THREAD

**Issue by funyapu** [pxgrid/aigis#87]
I would like to create README file in markdown and show them both in Github and Aigis.
Do you have any function I can do it with single markdown file and still indexed in Aigis index list?

For example,
- create .md file and import it in readme.styl and write index config in readme.styl.
- add config to import .md and its index config.

**Comment by geckotang** [comment]
@funyapu If you want to create `/your-styleguide/index.html` from `README.md`, you can write the following setting.

```yml
# aigis_config.yml
dest: ./your-styleguide
index: ./README.md
```

How about this?
