### ISSUE TITLE
include/exclude option for source files with glob pattern

### ISSUE THREAD

**Issue by ktsn** [pxgrid/aigis#95]
Hello, thank you for your great tool. I feel really comfortable to use it.

I think it would be very nice if we can specify glob pattern for source files in order to handle complex directory structures. Also exclude option would be useful.

Maybe for example:

```yaml
source_include:
  - src/**/*.scss
source_exclude:
  - src/sub_project/**
```

How would you feel about this?

**Comment by nakajmg** [comment]
Hello, thank you for good idea!

> I think it would be very nice if we can specify glob pattern for source files in order to handle complex directory structures. Also exclude option would be useful.

I agree with you 👍 

However that example is included breaking change.
I think `source` and `source_exclude` are better way:

```yml
source:    
    - src/**/*.scss
source_exclude:                    
    - src/sub_project/**
```

also make `source_include` an alias for `source` optionally.

I'll planning implement `source_exclude` options on next update 👍
